---
abstract: 'Catalyst-Orochi Integration'
author:
  - 'Daisuke Maki C<< <daisuke@endeworks.jp> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Model-Orochi
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.8
  Orochi: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.00002
